### ISSUE TITLE
关于dns分流

### ISSUE THREAD

**Issue by kevin198346** [Rabbit-Spec/Clash#1]
我surge使用你的配置一直很不错，clash我经过多次chatgpt修改，
  nameserver-policy:
    '+geoip,cn': # 根据 GeoIP 数据路由到国内 DNS
     - 223.5.5.5   # 阿里DNS
     - 119.29.29.29 # 腾讯DNS
    '+geoip,!cn': # 根据 GeoIP 数据路由到国外 DNS
      - 8.8.8.8     # Google DNS
      - 1.1.1.1     # Cloudflare DNS
  cache: true
  cache-size: 2048 
可以试用一下，国内走阿里，国外走谷歌。

**Comment by Rabbit-Spec** [comment]
国外DNS解析正常情况下都是由机场服务端完成的，不在本地解析。不配置国外域名由Google DNS解析对使用没有影响。

**Comment by kevin198346** [comment]
我试用一段你的配置，感觉你的很简单明了，虽然大部分看不懂，我就设置个fake ip,meta内核ok吗？

**Comment by Rabbit-Spec** [comment]
OK的
